### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Philip19692022** [BarGabriel/SipServer#1]
![image](https://user-images.githubusercontent.com/102969431/161548476-d01c16ac-22a7-4f8a-ac00-b19ab8bb5ea9.png)
I get an error when running it.

**Comment by BarGabriel** [comment]
Try running with this args:
.\SipServer.exe --ip=192.168.1.123 --port=5060

**Comment by Philip19692022** [comment]
Ok it starts on my laptop but when trying on my server i get the following error:
![image](https://user-images.githubusercontent.com/102969431/161733704-2c2f3850-2c8e-4172-81b0-5b3e32cb4421.png)

**Comment by Philip19692022** [comment]
When running on my Laptop i am tryiing to register with a client on my phone i get  map options not found:
![image](https://user-images.githubusercontent.com/102969431/161735814-7728f3d6-0e87-4c13-afd2-bb8680ee22bd.png)

**Comment by BarGabriel** [comment]
Unfortunately the server doesn't handle sip options request right now..
You can see the supported requests at SipMessageTypes header file.

**Comment by Philip19692022** [comment]
Is it possible to add?
