### ISSUE TITLE
Segmentation Fault when trying to call itself

### ISSUE THREAD

**Issue by glassesq** [BarGabriel/SipServer#7]
something like:
```
From: <sip:username@provider.com:7061>;tag=oxv2p2rk6jnx39ppxrmk
To: <sip:username@provider.com:7062>
```
this will cause segmentation fault, if username is registered before

**Comment by BarGabriel** [comment]
Hi, when I tried to perform a call from a client to himself it was handled well.

When a client sends a registration request, the server saves his number and socket and when an invite request will be sent from the client to the server to himself, the server just will take the destination number (from the To header) and will send him the request so something like this:

```
From: <sip:username@provider.com>;tag=oxv2p2rk6jnx39ppxrmk
To: <sip:username@provider.com>
```
should be handled well without segmentation fault if the client has been registered before.

If you want you can upload the whole packets headers and I will try to help you.

**Comment by glassesq** [comment]
Hi, sorry for not providing details before.
I am running SipServer on Ubuntu 20.04, and I started the program with `./SipServer --ip [MY_IP] --port 9012`. 

> (Please replace [MY_IP] with a real IP address like 1.2.3.4)

First I tried to send a REGISTER request, and it was successfully processed.

MY_IP:7063 ----udp---> MY_IP:9012
```
REGISTER sip:provider.com SIP/2.0
Via: SIP/2.0/UDP [MY_IP]:7063;rport=7063;branch=z9hG4bKN3T1XG86XEDWGJCQ8PC4
From: <sip:caller@provider.com>;tag=myhoiuahdwq7bq2oma64
To: <sip:caller@provider.com>
Call-ID: 2daynrg6irltx5q1oswgil41t6ft1t
CSeq: 101 REGISTER
Content-Length: 0
Max-Forwards: 70
Contact: <sip:contact@[MY_IP]>
Date: Tue, 14 Feb 2023 17:40:27 GMT
```

I received a 200 OK response. 

MY_IP:9012 ----udp---> MY_IP:7063
```
SIP/2.0 200 OK
Via: SIP/2.0/UDP [MY_IP]:7063;rport=7063;branch=z9hG4bKN3T1XG86XEDWGJCQ8PC4;received=[MY_IP]
From: <sip:caller@provider.com>;tag=myhoiuahdwq7bq2oma64
To: <sip:caller@provider.com>;tag=fa37JncCH
Call-ID: 2daynrg6irltx5q1oswgil41t6ft1t
CSeq: 101 REGISTER
Content-Length: 0
Max-Forwards: 70
Contact: <sip:caller@[MY_IP]:9012;transport=UDP>
Date: Tue, 14 Feb 2023 17:40:27 GMT
```
I can see a `New Client: caller` on the terminal running SipServer.

---
Then I started a new UDP socket and tried to send a new INVITE request. That is when the segmentation fault occurred.

MY_IP:7064 ----udp---> MY_IP:9012
```
INVITE sip:caller@provider.com SIP/2.0
Via: SIP/2.0/UDP [MY_IP]:7064;rport=7064;branch=z9hG4bKOT78L04DQ2TRFZ4HMAZY
From: <sip:caller@provider.com>;tag=do6nnvzupch4ndlctufx
To: <sip:caller@provider.com>
Contact: <sip:caller@provider.com>
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Call-ID: ke48sk8dlv4f4hhddyk485qhig7wtu
CSeq: 101 INVITE
Content-Length: 0
Date: Tue, 14 Feb 2023 17:40:34 GMT
```

I received no response from SipServer, and the SipServer program crashed, showing a `Segmentation fault (core dumped)`
Thank you for your help!

**Comment by BarGabriel** [comment]
Everything seems valid except that the INVITE message should contain SDP in addition to SIP headers.

The "OnInvite" handler does a cast to SdpMessage and try to read its members, but in case that the cast has been failing because the message doesn't contain SDP information, we will get a segmentation fault.

Maybe this is the problem?

Anyway, I will handle this edge case and will throw an informative exception.

**Comment by BarGabriel** [comment]
I pushed a fix for the problem I described above, you can check if it handles your case.

**Comment by glassesq** [comment]
Thank you!
